version: '3.4'

services:
  site:
    image: joomla
    #restart: always
    networks:
      - lan
      - wan
    ports:
      - "80:80"
    environment:
      JOOMLA_DB_HOST: "db"
      JOOMLA_DB_NAME: "joomla"
      JOOMLA_DB_USER: "user"
      JOOMLA_DB_PASSWORD: "dbpass"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 0s

  db:
    image: mysql:5.6
    #restart: always
    networks:
      - lan
    environment:
      MYSQL_ROOT_PASSWORD: "rootpass"
      MYSQL_DATABASE: "joomla"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "dbpass"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 0s

networks:
  lan: 
  wan:
    #external: True


# vim: ft=yaml tw=80 et ts=2 sw=2 sts=2
